import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateBetterAuthTables1785801600000 implements MigrationInterface {
  name = 'CreateBetterAuthTables1785801600000';

  async up(queryRunner: QueryRunner): Promise<void> {
    // AI modified: preserve the MySQL schema generated by Better Auth 1.6.25 inside the project's migration lifecycle.
    await queryRunner.query(
      'CREATE TABLE `user` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `emailVerified` boolean NOT NULL, `image` text NULL, `createdAt` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `IDX_better_auth_user_email` (`email`), PRIMARY KEY (`id`)) ENGINE=InnoDB',
    );
    await queryRunner.query(
      'CREATE TABLE `session` (`id` varchar(36) NOT NULL, `expiresAt` timestamp(3) NOT NULL, `token` varchar(255) NOT NULL, `createdAt` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` timestamp(3) NOT NULL, `ipAddress` text NULL, `userAgent` text NULL, `userId` varchar(36) NOT NULL, UNIQUE INDEX `IDX_better_auth_session_token` (`token`), INDEX `session_userId_idx` (`userId`), PRIMARY KEY (`id`), CONSTRAINT `FK_better_auth_session_user` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE) ENGINE=InnoDB',
    );
    await queryRunner.query(
      'CREATE TABLE `account` (`id` varchar(36) NOT NULL, `accountId` text NOT NULL, `providerId` text NOT NULL, `userId` varchar(36) NOT NULL, `accessToken` text NULL, `refreshToken` text NULL, `idToken` text NULL, `accessTokenExpiresAt` timestamp(3) NULL, `refreshTokenExpiresAt` timestamp(3) NULL, `scope` text NULL, `password` text NULL, `createdAt` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` timestamp(3) NOT NULL, INDEX `account_userId_idx` (`userId`), PRIMARY KEY (`id`), CONSTRAINT `FK_better_auth_account_user` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE) ENGINE=InnoDB',
    );
    await queryRunner.query(
      'CREATE TABLE `verification` (`id` varchar(36) NOT NULL, `identifier` varchar(255) NOT NULL, `value` text NOT NULL, `expiresAt` timestamp(3) NOT NULL, `createdAt` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `verification_identifier_idx` (`identifier`), PRIMARY KEY (`id`)) ENGINE=InnoDB',
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    // AI modified: remove foreign-key dependents before the Better Auth user table.
    await queryRunner.query('DROP TABLE `account`');
    await queryRunner.query('DROP TABLE `session`');
    await queryRunner.query('DROP TABLE `verification`');
    await queryRunner.query('DROP TABLE `user`');
  }
}
